services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.13
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    networks:
      - elk

  logstash:
    image: docker.elastic.co/logstash/logstash:7.17.13
    container_name: logstash
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    ports:
      - "5044:5044"
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.13
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Ban@4577
      POSTGRES_DB: vppdb
    ports:
      - "5433:5432"
    networks:
      - elk
    volumes:
      - postgres_data:/var/lib/postgresql/data

  vpp-app:
    build: .
    container_name: vpp-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/vppdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Ban@4577
      SPRING_ELASTICSEARCH_URIS: http://elasticsearch:9200
    depends_on:
      - postgres
      - elasticsearch
      - logstash
    networks:
      - elk
    ports:
      - "8181:8181"

networks:
  elk:
    driver: bridge

volumes:
  postgres_data: