spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/vppdb
    username: postgres
    password: Ban@4577
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        transaction.jta.platform: org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform
  application:
    name: vpp-battery-api
  elasticsearch:
    uris: http://elasticsearch:9200
    connection-timeout: 30s
    socket-timeout: 60s

logging:
  level:
    root: INFO
    io.powerledger.vpp: DEBUG

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

server:
  compression:
    enabled: true
    min-response-size: 300
    mime-types:
      - application/json
      - application/xml
      - text/html
      - text/xml
      - text/plain
      - text/css
      - text/javascript
      - application/javascript
  port: 8181

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    prometheus:
      enabled: false